services:
    orchestrator:
        image: ghcr.io/brewcoua/webwisp-orchestrator:master
        container_name: orchestrator

        ports:
            - '3000:3000'

        networks:
            - webwisp

        depends_on:
            rabbitmq:
                condition: service_healthy

        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/health']
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 30s

        env_file:
            - path: ./.env
              required: false
            - path: ./.env.orchestrator
              required: true

    worker:
        image: ghcr.io/brewcoua/webwisp-worker:master

        deploy:
            mode: replicated
            replicas: 2

        networks:
            - webwisp

        depends_on:
            rabbitmq:
                condition: service_healthy

        restart: on-failure

        env_file:
            - path: ./.env
              required: false
            - path: ./.env.worker
              required: true

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3-management

        ports:
            - '5672:5672'
            - '15672:15672'

        networks:
            - webwisp

        healthcheck:
            test: ['CMD', 'rabbitmqctl', 'status']
            interval: 10s
            timeout: 10s
            retries: 3

        env_file:
            - path: ./.env
              required: false
            - path: ./.env.rabbitmq
              required: false

networks:
    webwisp:
        driver: bridge
