export const TASK_REPOSITORY = Symbol('REPOSITORIES.TASK')
export const TASK_QUEUES_REPOSITORY = Symbol('REPOSITORIES.TASK_QUEUES')
export const TRACES_REPOSITORY = Symbol('REPOSITORIES.TRACES')
export const TASK_GROUP_REPOSITORY = Symbol('REPOSITORIES.TASK_GROUP')
