name: Publish

on:
    workflow_dispatch:

env:
    REGISTRY: ghcr.io

jobs:
    publish-orchestrator:
        name: Publish
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write
            attestations: write
            id-token: write

        strategy:
            matrix:
                package: [orchestrator, worker]

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Extract metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ github.repository }}-${{ matrix.package }}

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              id: push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./packages/${{ matrix.package }}/Dockerfile
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}

            - name: Generate artifact attestation
              uses: actions/attest-build-provenance@v1
              with:
                  subject-name: ${{ env.REGISTRY }}/${{ github.repository }}-${{ matrix.package }}
                  subject-digest: ${{ steps.push.outputs.digest }}
                  push-to-registry: true
